### ISSUE TITLE
Development vs Production - how we architect

### ISSUE THREAD

**Issue by rgrp** [cybergreen-net/infrastructure#3]
Three options:
- Duplicate infrastructure: `dev.bits.cg.net` s3 bucket vs `bits.cg.net`
- Partition infrastructure e.g. an S3 bucket has `/dev/` and `/prod/`
- A mixture of these

Need to work this out and agree naming and setup

**Comment by rgrp** [comment]
@chorsley @kxyne any thoughts here?

My initial inclination is separate buckets rather than directories in a bucket but we can accommodate either.

**Comment by chorsley** [comment]
Had been thinking to keep the /dev/ and /prod/ directory separation in a single bucket here for simplicity and because we have it already, but not adverse to the idea of separate buckets if we see some benefit there. 

The next step I'll kick off is a quick analysis doc of each stage of the ETL, aggregator, and website, determine their current state of infrastructure and how that's currently configured, how flexible the code driving each of them is, and which will need stand-alone instances created on demand.

**Comment by rgrp** [comment]
@chorsley great. I'm inclined to separate buckets. Reasoning:

- Easier to partitions permissions correctly and not make errors (e.g. test infrastructure cleanly separated from production)
- Publicly visible stuff like bits.cybergreen.net does not end up with dev and test stuff in it
- Separate infrastructure encourages us to do setup and teardown of infrastructure making our process more repeatable and more reusable by others

**Comment by chorsley** [comment]
I've been having a look for other opinions on subdirs in a single bucket vs multiple buckets. I was leaning towards separate buckets created at runtime also, but then found http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html:

> The high-availability engineering of Amazon S3 is focused on get, put, list, and delete operations. Because bucket operations work against a centralized, global resource space, it is not appropriate to create or delete buckets on the high-availability code path of your application. It is better to create or delete buckets in a separate initialization or setup routine that you run less often.

I'm now thinking a hybrid solution:

* Two buckets of each type, "prod" and "dev", both permanently established.
* Under each bucket, we still have directory separations. There would be:
    * prod.bucket/prod
    * dev.bucket/dev
    * dev.bucket/test
    * dev.bucket/user1
    * dev.bucket/user2

This still allows multiple devs to have their own space to play in without needing to instantiate a new bucket or tread on anyone else's toes.

So, to the good points you made, and how we might accomplish them with the above:

> Easier to partitions permissions correctly and not make errors (e.g. test infrastructure cleanly separated from production)

We can set permissions both on the bucket and directory level. Each data pipeline component will be configured via Ansible + env variables to point to one particular location via config file. 

We can also ensure that only a single account known to the automated prod jobs (e.g. cg_prod user) has write access into prod.bucket/prod.

> Publicly visible stuff like bits.cybergreen.net does not end up with dev and test stuff in it

The two-bucket solution should cover this off.

> Separate infrastructure encourages us to do setup and teardown of infrastructure making our process more repeatable and more reusable by others

As above, since dynamic bucket creation does not seem kosher, we can establish these two buckets permanently. Directories could be more dynamic if we wish.  We should do more dynamic setup and teardown for other infra where it makes sense, too (e.g. EC2 hosts).

Feedback very welcome.

**Comment by rgrp** [comment]
@chorsley i'm not sure there are any implications from http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html for us - unless i have misunderstood.

We are still only creating buckets infrequently - for prod and dev these are basically once-off and for test this is still not that frequently (in fact we could just create once and not delete). So I don't think there are any implications for HA stuff for us.

Summary: we could even create the prod dev and test buckets by hand - no need for automation. Whether we automate or not for prod and dev we are create once and leave in place and same can be true for test.

(It could be good practice for us to automate the creation and removal of these buckets even so because then we have *everything* automated but frankly it is not essential).

Summary:

- Having distinct buckets e.g. bits.* and dev.bits.* and test.bits.* does not imply they have to be constantly created and deleted. We can create once.
- Reading this and your comments I think we are generally in strong agreement 😄

**Comment by rgrp** [comment]
Moving to 5 Dec as did not happen in 28 Nov sprint.

**Comment by chorsley** [comment]
Yes, we can agree on that. Bucket creation will be manual, as there will not be many of them.

I suggest keeping a directory level below the bucket (e.g. /prod/, /dev/) etc, as this allows is to set up a directory per developer if we'd like to, or if we wish to have parallel structures in the future for any reason. So to start we'd have:

* dev.bits.*/dev/, dev.bits.*/user1/, dev.bits.*/user2/
* test.bits.*/test/
* prod.bits.*/prod/

**Comment by rgrp** [comment]
@chorsley:

- I'd still suggest we automate the bucket creation - even if we only run it once (by automate I mean we create from script rather than in console)
- i'm still -1 on the folders below at least on production. This makes it messy for end users e.g. `bits.cg.net` would have a simple structure like:

```
/latest/openntp.csv
```

rather than this which is more confusing for users to browse:

```
/prod/latest/openntp.csv
```

Generally, why do we want to have:

```
test.bits.cg.net/test/
```

It just seems repetitive. If we do need a general dumping ground we can always boot a separate s3 bucket.

If we do need parallel structures in future we can refactor to support that (should be pretty easy esp if we support subpaths in our config for our tools - which is easy to do). Let's KISS to start with and add subfolders if we really need it at some point later.

All that said, at least on the non-prod bucket this does not matter that much - key thing is we move forward.

**Comment by chorsley** [comment]
Understood. It's always good to have symmetry on all envs (e.g. directory depth), but I can see the point on simplicity in prod paths.  In dev, we're still likely to want multiple dirs off the root.

As long as all components both on ETL and aggregator can be configured for both  bucket name + a root dir, and don't have any dependencies on directory depth, that should be okay.  Let's proceed with data straight under the bucket root in prod and test (e.g. /latest/openntp.csv), and see if we come against any hurdles in practice.

**Comment by rgrp** [comment]
FIXED. Agreed:

```
bits.{cg.net}   # prod
dev.bits.{cg.net}  # dev
test.bits.{cg.net}
```

Example file structure in prod:

```
/latest/openntp.csv   # example file structure
```

We will build support into all tools that use buckets to allow for an optional arbitrary file prefix on all buckets so we can use directories if we need to.
